### ISSUE TITLE
Not on Bower

### ISSUE THREAD

**Issue by davidrhoderick** [ejeinc/Angular360#1]
I am using Bower on a project that would benefit from this plug-in but this is not actually on Bower.  If you do a search for "Angular360", nothing comes up.  I tried "angular-360" as well and anything with "360."  Looks like you are almost there with a bower.json file but it's not online.

**Comment by niusounds** [comment]
Hi.
I registered Angular360 to bower repository.
You can install with:
```
$ bower install angular360
```

thanks.

**Comment by davidrhoderick** [comment]
Ok I tried to install it and it looks like it went through but I don't think your CSS file is linked in your bower.json so wiring dependencies in grunt through the bower files won't work.
